### ISSUE TITLE
First result search doesn't work (\futurama) with URL searches.

### ISSUE THREAD

**Issue by DabaMcD** [duckduckgo/duckduckgo-help-pages#100]
From https://help.duckduckgo.com/results/syntax/

> Use **\\** to go to directly to the first search result. For example, **\futurama**

While the above works if searched from duckduckgo.com, it does not work if you just do a "default search engine" search by putting **\futurama** directly in the URL. I tried searching for **\futurama** and it just takes me to the **futurama** search results.

**Comment by moollaza** [comment]
Using Firefox, Chrome and Safari, this works as expected for me. Entering **\futurama** in the URL bar, and pressing entire directs me to the Wikipedia article for Futurama.

It may be that your browser is preventing that specific syntax from working?
