### ISSUE TITLE
Conversion searches turn into image searches

### ISSUE THREAD

**Issue by ivydrivey** [duckduckgo/duckduckgo-help-pages#103]
![image](https://user-images.githubusercontent.com/92343720/146271611-e549e089-7b47-4e67-9a34-8b15b718b868.png)

Rather strange behavior if you input a conversion for an unsupported currency, provides image results instead of Instant Answer.
It currently seems as if all searches regarding cryptocurrency conversions resolve into image searches.

**Comment by moollaza** [comment]
Thanks for reporting. Our cryptocurrency conversion Instant Answer is currently being fixed and will be live shortly. After that, this will no longer happen.

I'm going to close this issue, as it's not related to the repo content (help pages).
