### ISSUE TITLE
Broken link on "Sources" Support Page

### ISSUE THREAD

**Issue by Aarav-USA** [duckduckgo/duckduckgo-help-pages#107]

**Comment by Aarav-USA** [comment]
There is a broken link that should refer to the sources that DuckDuckGo uses to aggregate searches. Since the link is broken (duck.com/ia) it forwards to "DuckDuckGo.com". The broken link under "four hundred sources" needs to be updates. The support page with the broken link is reffered to below.

Support Page: https://help.duckduckgo.com/duckduckgo-help-pages/results/sources/

**Comment by moollaza** [comment]
This has been fixed.
