### ISSUE TITLE
Instant Answers and Other Features - examples not work

### ISSUE THREAD

**Issue by borisov87** [duckduckgo/duckduckgo-help-pages#11]
In this page some examples not work
https://help.duckduckgo.com/duckduckgo-help-pages/features/instant-answers-and-other-features/

 factual information link 
https://duckduckgo.com/?q=calories+in+2+eggs&ia=web

 words that rhyme together
https://duckduckgo.com/?q=rhyme+list&ia=web

**Comment by tagawa** [comment]
Hi @borisov87. Thanks very much for spotting and reporting this. I've just submitted a fix for it: https://github.com/duckduckgo/duckduckgo-help-pages/pull/12

**Comment by borisov87** [comment]
I was happy to help :)
