### ISSUE TITLE
`!tumbview` not working

### ISSUE THREAD

**Issue by JapanYoshi** [duckduckgo/duckduckgo-help-pages#145]
I tried using the ! shortcut for “Tumbview”, but it showed me a “page not found” page from something called “Nearly Free Speech”.

**Comment by dharrison27** [comment]
> I tried using the ! shortcut for “Tumbview”, but it showed me a “page not found” page from something called “Nearly Free Speech”.

Hi! Just another user like you, chiming in.

Have you submitted a request for a bang update? Check it out here: [https://duckduckgo.com/newbang](https://duckduckgo.com/newbang)

**Comment by JapanYoshi** [comment]
Perhaps if they don’t renew it by June next year, mention of Tumbview should be removed from the help pages.

**Comment by moollaza** [comment]
Thanks for reporting. I've notified our staff to remove this next time we update the bangs.

In the future, you can report this via https://duckduckgo.com/newbang
