### ISSUE TITLE
Default font changed

### ISSUE THREAD

**Issue by refriedfood** [duckduckgo/duckduckgo-help-pages#150]
Change it back to arial, please. ew.

**Comment by moollaza** [comment]
Hello, I'm not sure what font you're referring to, but the font on duckduckgo.com has not changed. If you'd like to use Arial, you can enable that on our settings page: https://duckduckgo.com/settings#appearance

**Comment by refriedfood** [comment]
I don't use cookies, nor do I stay logged into anything.

Before: https://ptpimg.me/935el7.png

After: https://ptpimg.me/bnk113.png

You changed your default font, it looks like shit, therefore I'm not using your engine. Pretty simple.

**Comment by moollaza** [comment]
> I don't use cookies, nor do I stay logged into anything.

That’s not a problem, you can specify DuckDuckGo setting with URL parameters if you don’t want to use any cookies. It looks like you already have several settings set in that screenshot. 

Please try adding ka=a to the URL, that should set the font to Arial.

**Comment by refriedfood** [comment]
Seeing as you knew that I knew how to go about making parameters, did you try to do that _yourself_ before suggesting it? That was how I knew it was changed to begin with.

https://i.imgur.com/8BiWunR.png

**Comment by moollaza** [comment]
> Seeing as you knew that I knew how to go about making parameters, did you try to do that _yourself_ before suggesting it? That was how I knew it was changed to begin with.

Yes, I did, but I had a typo in my message above. Sorry!

It should be `kt=a`. 

Give that a try and if it doesn't work, try removing your other settings to confirm it works on its own. If it does, then there might be a bug with the combination of settings you have. If you share your settings, I'll try and figure out what's going on.

**Comment by moollaza** [comment]
I spoke to a colleague and confirmed there's a known bug with the `ka=` parameter not working in some cases. That's the setting for the **link title font**. 

We're working on a fix, but if you want the whole page to use Arial, then `kt=a` should work, that's the setting for the page font.

Sorry about the inconvenience.
