### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by rakleed** [duckduckgo/duckduckgo-help-pages#162]
Could you please add a dark theme to the site? Because using your site at night or in dark rooms is very unpleasant because of the bright white background.

**Comment by moollaza** [comment]
Hello! DuckDuckGo already has a dark theme. You can access it from the results page:

1. Click the "Settings" button below the searchbox
2. Click the black box with white lines to select the dark theme

![Theme Select](https://user-images.githubusercontent.com/873785/225760976-c412bf55-f9fb-4b75-982f-933e970fc6fc.png)

**Comment by rakleed** [comment]
@moollaza I know that the main site has a dark theme. But the [Help page](https://help.duckduckgo.com/) does not have a dark theme, which is why I create an issue to this repository.

**Comment by moollaza** [comment]
Thanks for clarifying. We don’t currently have plans to add a dark theme to the help pages, but it’s in our radar!
