### ISSUE TITLE
DuckDuckBot rDNS + IPv6

### ISSUE THREAD

**Issue by jaw-sh** [duckduckgo/duckduckgo-help-pages#172]
It is standard practice for web crawling bots to provide an rDNS entry on their IPs.

<https://developers.google.com/search/docs/crawling-indexing/verifying-googlebot>
<https://www.bing.com/webmasters/help/how-to-verify-bingbot-3905dc26>
<https://yandex.com/support/webmaster/robot-workings/check-yandex-robots.html>

While DDG provides a list of IPs to whitelist, it does not follow the convention. The IPs belong to Microsoft and provide no rDNS entry at all, making them indistinguishable from other web traffic.

See: https://whatismyipaddress.com/ip/40.76.162.191

Also, please add IPv6 support. IPv4 depletion was about ten years ago.

**Comment by moollaza** [comment]
Thanks for flagging. I alerted our ops team and this has been resolved.
