### ISSUE TITLE
Customize searching via parameters, not working at all

### ISSUE THREAD

**Issue by airvzxf** [duckduckgo/duckduckgo-help-pages#176]
Hi,

I'm trying to customize the search page based on the official documentation [setting and URL parameters](https://help.duckduckgo.com/settings/params/). Some parameters are not working, specially about the color.

This is my example with custom color:

https://duckduckgo.com/?sites=wikipedia.org&kp=-2&kz=1&kc=1&kav=1&kn=-1&kf=fw&kaf=1&kac=1&kj=%232f4f4f&kx=e&k7=%23fffeeb&k8=%23ff0000&k9=%23fffeeb&kaa=%234bb503&ks=t&kw=s&km=m&ka=h&ku=1&kt=p&ko=s&k1=-1&kv=1&kaj=m&t=rovisoft.net&q=Mexico&atb=v245-1

Working good:
- Header | kj = %232f4f4f
- Background | k7 = %23fffeeb
- URLs | kx = e

Not working:
- URLs | kx = %23fffeeb
- Text | k8 = %23ff0000
- Links | k9 = %23fffeeb
- Visited links | kaa = %234bb503
- Link font | ka = h for Helvetica

Evidence:

![image](https://user-images.githubusercontent.com/831380/221475473-e9a7016e-15ef-4df5-b806-2833c1e8de85.png)

**Comment by moollaza** [comment]
Thanks for reporting! 

You can remove the `%23` from the URL. Looks like that's a mistake in the docs 👍🏽 

Regarding the `ka` setting, that's actually a bug. I've flagged it internally and we should have a fix out soon.

Thanks

**Comment by airvzxf** [comment]
It works, thank you. I applied and it appears as desired:

https://duckduckgo.com/?sites=wikipedia.org&kp=-2&kz=1&kc=1&kav=1&kn=-1&kf=fw&kaf=1&kac=1&kj=2f4f4f&kx=ff00ff&k7=fffeeb&k8=ff0000&k9=00ff00&kaa=0000ff&ks=t&kw=s&km=m&ka=h&ku=1&kt=p&ko=s&k1=-1&kv=1&kaj=m&t=rovisoft.net&q=Mexico&atb=v245-1

Text | k8 = ff0000 | Red
Links | k9 = 00ff00 | Green
Visited links | kaa = 0000ff |  Blue
URLs | kx = ff00ff | Pink

![Screenshot with custom colors](https://user-images.githubusercontent.com/831380/225791101-04a10977-f28c-4bea-ba39-b0a39ee45e47.png)
