### ISSUE TITLE
offer a sustainable alternative to ads in master/_docs/settings/adblockers.md

### ISSUE THREAD

**Issue by Gaspartame** [duckduckgo/duckduckgo-help-pages#192]
Please add a proposition to keep blocking ads and make regular donations to duckduckgo, with an advice for a donation amount.
A lot of people don't want to see ads, and for a reason, also a lot of people don't want to generate profit for microsoft, so please offer them this option. It could be in the interest of all involved.

**Comment by moollaza** [comment]
Hi @Gaspartame, you can disable ads in our [Settings](https://duckduckgo.com/settings#general) if you don't want to see them. We cannot accept donations, though. Thanks
