### ISSUE TITLE
Japanese Ligature BUG

### ISSUE THREAD

**Issue by paseri3739** [duckduckgo/duckduckgo-help-pages#286]
font-feature-settings:"liga","dlig" caused BAD rendering.
<img width="1122" alt="Screenshot 2024-01-23 at 20 57 27" src="https://github.com/duckduckgo/duckduckgo-help-pages/assets/71875149/c1686766-172e-4783-9feb-e3ce03dc3cfe">
<img width="1122" alt="Screenshot 2024-01-23 at 20 57 34" src="https://github.com/duckduckgo/duckduckgo-help-pages/assets/71875149/aa8734f6-8bf7-46ec-b27d-ccd592e2fb1d">

reference: https://heistak.github.io/your-code-displays-japanese-wrong/otherthings.html

**Comment by tagawa** [comment]
Hi @paseri3739. Sorry for the delay in getting back to you and thank you very much for pointing this out and providing the screenshots. I’ve passed it on to team working on this so they can look into it further.

**Comment by paseri3739** [comment]
Thank you for your reply. I am a heavy user of DDG so I am happy to contribute to the project!

**Comment by tagawa** [comment]
That’s very kind – thank you!

**Comment by tagawa** [comment]
Hi again @paseri3739. Just wanted to confirm that this is now fixed:
https://duckduckgo.com/?kad=ja_JP

Thanks again for your help!

**Comment by paseri3739** [comment]
Good! That's completely solved!
<img width="1470" alt="Screenshot 2024-04-11 at 20 14 06" src="https://github.com/duckduckgo/duckduckgo-help-pages/assets/71875149/5491afda-81bf-4814-8902-fbe0781cb94a">
