### ISSUE TITLE
i need a page refresher program.

### ISSUE THREAD

**Issue by ham1tcagdas** [duckduckgo/duckduckgo-help-pages#309]
Hello i am a service provider on internet store and i need to refresh my webpage to show myself online. i m switched to browser duckduckgo and since extensions not allowed i dont know how to run a javascript code on that browser. Can someone help me about it.

// ==UserScript==
// @name G2GCHATREFRESHER Script
// @match *g2g.com
// @exclude example.com
// @version      4.0
// @description  G2GPageRefresher
// @run-at document-start
// ==/UserScript==
if (window.location.toString() === "https://www.g2g.com/chat/#/") {
  setTimeout(function(){
   window.location.reload(1);
}, 480000);
}

Thats a working javascript code all i need to know how can i make this run on duckduckgo browser.

**Comment by tagawa** [comment]
Hi @ham1tcagdas. Sorry but I’m afraid it’s not possible to run extensions or JavaScript UserScripts in the DuckDuckGo browser at the moment.
