### ISSUE TITLE
DuckDuckGo Browser - Windows 10 - "Fire"/Clear Data Button - The application fails to re-open after the clearing data process completes

### ISSUE THREAD

**Issue by zhayes0887** [duckduckgo/duckduckgo-help-pages#312]
When a user clicks the "Fire"/Clear Data Button in the Duck Duck Go Browser application on Windows 10, the browser window is not re-opened automatically like it did previously or how it operates currently on Windows 11.

**Reproduction Steps:**

1. Open the Duck Duck Go Browser on a Windows 10 PC
2. Click the "Fire"/Clear Data button to the left of the window resize buttons on the top tool/title bar of the window.
3. Click the "Clear" Button on the popup asking to confirm to "Close Tabs and Clear Data" 
4. The "Clearing Data" progress window opens and completes

**Observed Result:**

- The browser window is not restored and the user must manually "re-open" the browser again

**Expected Result:**

- The browser window is automatically re-opened after the "Clearing Data" Process completes without user interaction.

**App Version Tested:** 0.75.1

**Windows 10 Info:**
-  Edition: Windows 10 Pro
- Version: 22H2
- OS Build: 19045.4291

**Windows 11 Info:**
-  Edition: Windows 11 Home
- Version: 23H2
- OS Build: 22631.3374

**Comment by tagawa** [comment]
Hi @zhayes0887. Thank you for reporting this in such detail. I’ve forwarded your report to our Windows team to investigate, so I’ll close the task here.

**Comment by zhayes0887** [comment]
@tagawa Apologies for reporting here but I did not see any other place I could report an issue on the Windows app. As I find issues is it okay to report them here or where should that be done in the future?

**Comment by tagawa** [comment]
@zhayes0887 No need to apologize! Your detailed report is much appreciated. In future, if you use the “Send Feedback” option from the browser’s “Help” menu, that should go straight to the developers.

![Screenshot 2024-04-12 at 17 11 10](https://github.com/duckduckgo/duckduckgo-help-pages/assets/94173/bb4469eb-6867-4690-b66d-9b0bcc8e0b6c)
