### ISSUE TITLE
duck search doesnt work most lf the time

### ISSUE THREAD

**Issue by Chad90b** [duckduckgo/duckduckgo-help-pages#336]
duck sarch doesnt work most of the time. this issue has grown lately and is now so bad that one might switch to a different search engine instead of spamming the search button in hopes that it will resolve itself.

searching for anything in region:any returns the following error:

Sorry, we ran into an error displaying these results. Click here to try again.

**Comment by Struppi** [comment]
dito. I got no search results

**Comment by tagawa** [comment]
Thanks for making us aware. We're currently experiencing an issue with DuckDuckGo Search that is affecting results. Thanks for your patience while we sort it out.

**Comment by tagawa** [comment]
Looks like things are returning to normal. Thanks for being patient while it was being fixed.
