### ISSUE TITLE
Browser crashing after clicking on update. 

### ISSUE THREAD

**Issue by kkhurramali** [duckduckgo/duckduckgo-help-pages#504]
<img width="1002" alt="Screenshot 2024-12-12 at 10 34 11 PM" src="https://github.com/user-attachments/assets/590aea77-e5c0-4ba7-b533-3de19f12417b" />

**Comment by tagawa** [comment]
Hi @kkhurramali. Thanks for reporting this and providing a screenshot. I’ve just forwarded it to the developers to look into.
