### ISSUE TITLE
problem with Safe search

### ISSUE THREAD

**Issue by ebs111222** [duckduckgo/duckduckgo-help-pages#95]
hi,
first of all great work with the search engine, thanks.
there is a problem with Safe search even when its on, porn sites a pear.
for example:
https://duckduckgo.com/?q=sec+chat&kp=1&ia=web
is there any way to fix that?
thanks.

**Comment by moollaza** [comment]
Thanks for pointing this out. I've notified our devs. I'm going to close this issue as it's off-topic for the repo.

In the future, please report feedback via the "Feedback" button in the bottom-right corner of our Search Results page.
