### ISSUE TITLE
Mathematical operations

### ISSUE THREAD

**Issue by alediemmee** [duckduckgo/duckduckgo-help-pages#96]
Hello, I'd like to suggest to insert the Mathematical operations on DuckDuckGo.
On other search engine if I type 3+3 I can see the results on the page. 
It is very useful and faster to open a calculator app on my notebook.

**Comment by tagawa** [comment]
Hi @alediemmee. This is actually already possible. In DuckDuckGo Search, if you search for mathematical operations (with or without spaces) the answer is displayed, as well as an in-built calculator.

Example: [3+3](https://duckduckgo.com/?q=3%2B3&ia=calculator)

<img width="968" alt="DuckDuckGo Search calculator." src="https://user-images.githubusercontent.com/94173/128616277-2bfbac5a-38ee-4bcc-ac83-f039ac7118d1.png">

**Comment by Chaython** [comment]
Calculator is not always brought to top, anyway to resolve it?
Also should add more contextual support such as 1 billion pounds to kilograms, I found out 1b/ billion is supported for currency[xe.com] but the calculator doesn't.
I mostly use billions when determine, p/s p/e etc of stocks where for some reason stock sites are missing the data. For example on earnings release.

**Comment by moollaza** [comment]
Hey there, we're always working to improve our Instant Answers. The calculator and conversions should be working well, and we actually recently shipped more conversions triggers, but in instances where it doesn't work, please use the "Share Feedback" button in the bottom right corner of the search results page to report any issues to us.

Those feedback reports are reviewed daily and will help prioritize any fixes.

I'm going to close out this issue as it's unrelated to this repo, which is for our help pages.
